### PR TITLE
New CSH colors for Members.

### PR DESCRIPTION
**Pull request by mbillow**

### CODE REVIEW

**Comment by bencentra** [comment]
The `lighten()` for the .danger alerts and panels is a bit much. I'd go edit [this](https://github.com/mbillow/bootstrap-csh/blob/master/dev/members.less#L307-L308) and [this](https://github.com/mbillow/bootstrap-csh/blob/master/dev/members.less#L407-L415)

screen shot 2016-02-03 at 7 50 42 pm
screen shot 2016-02-03 at 7 50 55 pm

**Comment by bencentra** [comment]
It should be more like this:

screen shot 2016-02-03 at 7 54 00 pm
screen shot 2016-02-03 at 7 54 07 pm

**Comment by mbillow** [comment]
What percentages are those?

**Comment by bencentra** [comment]
Honestly, just tweak 'em until they look right. The percentages vary based on the starting color.

**Comment by mbillow** [comment]
:+1:

**Comment by bencentra** [comment]
:+1: indeed

**Pull request merged**
